apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  type: NodePort
  selector:
    app: kafka-consumer-ex
  ports:
    - port: 9292
      targetPort: 9292
      nodePort: 31472  # NodePort range is typically between 30000-32767

